#!/bin/bash
# auto-compound.sh - Nightly autonomous implementation loop
# Picks top task from implementation_plan.md, implements it, creates PR
# Runs nightly at 11:00 PM via launchd

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOG_FILE="/tmp/piol-auto-compound.log"
MAX_ITERATIONS="${1:-5}"
DATE_TAG=$(date '+%Y%m%d')

# Redirect all output to log file
exec > >(tee -a "$LOG_FILE") 2>&1

echo ""
echo "=========================================="
echo "Auto-Compound - $(date '+%Y-%m-%d %H:%M:%S')"
echo "=========================================="

cd "$PROJECT_ROOT"

# Preflight checks
echo "[compound] Running preflight checks..."

# 1. Check git status is clean
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "[compound] ERROR: Working directory not clean. Aborting."
  "$SCRIPT_DIR/notify.sh" "Aborted: dirty git state" "Compound Failed"
  exit 1
fi

# 2. Check we're on main
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" != "main" ]; then
  echo "[compound] WARNING: Not on main branch (on $CURRENT_BRANCH). Switching to main..."
  git checkout main
fi

# 3. Pull latest
echo "[compound] Pulling latest from main..."
git pull origin main --ff-only || {
  echo "[compound] ERROR: Failed to pull latest. Aborting."
  "$SCRIPT_DIR/notify.sh" "Aborted: git pull failed" "Compound Failed"
  exit 1
}

# 4. Parse implementation_plan.md for next task
echo "[compound] Analyzing implementation plan..."
TASK_INFO=$("$SCRIPT_DIR/analyze-report.sh" agent/implementation_plan.md) || {
  echo "[compound] No tasks to work on or all complete."
  "$SCRIPT_DIR/notify.sh" "All tasks complete!" "Compound Complete"
  exit 0
}

TASK_ID=$(echo "$TASK_INFO" | cut -d'|' -f1)
LINE_NUM=$(echo "$TASK_INFO" | cut -d'|' -f2)
TASK_DESC=$(echo "$TASK_INFO" | cut -d'|' -f3-)

echo "[compound] Selected task: $TASK_ID"
echo "[compound] Description: $TASK_DESC"
echo "[compound] Line number: $LINE_NUM"

# 5. Create feature branch
BRANCH_NAME="feat/compound-$DATE_TAG-$TASK_ID"
echo "[compound] Creating branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME"

# 6. Build the implementation prompt
IMPLEMENT_PROMPT="You are running in autonomous nightly mode. Complete this task from implementation_plan.md:

TASK: $TASK_DESC

Instructions:
1. Read agent/spec.md for full context
2. Read agent/implementation_plan.md to understand the task
3. Implement the task following existing patterns in the codebase
4. Run verification: bun run lint:fix && bun run typecheck
5. If tests are applicable, ensure they pass
6. Mark the task complete by changing [ ] to [x] on line $LINE_NUM of agent/implementation_plan.md
7. Say COMPLETE when done

Constraints:
- Follow patterns in CLAUDE.md
- No hardcoded colors (use design tokens)
- No hardcoded strings (use i18n)
- Keep changes focused on the task

If blocked, say BLOCKED with explanation."

# 7. Run implementation loop
echo "[compound] Starting implementation loop (max $MAX_ITERATIONS iterations)..."
"$SCRIPT_DIR/loop.sh" "$IMPLEMENT_PROMPT" "$MAX_ITERATIONS"
LOOP_EXIT=$?

# 8. Check if any changes were made
if git diff --quiet && git diff --cached --quiet; then
  echo "[compound] No changes made. Cleaning up branch."
  git checkout main
  git branch -D "$BRANCH_NAME"
  "$SCRIPT_DIR/notify.sh" "No changes made for: $TASK_DESC" "Compound Info"
  exit 0
fi

# 9. Run final verification
echo "[compound] Running final verification..."
bun run lint:fix || true
if ! bun run typecheck; then
  echo "[compound] WARNING: Typecheck failed. PR will be created for review."
fi

# 10. Commit changes
echo "[compound] Committing changes..."
git add -A
git commit -m "feat(agent): $TASK_DESC

Implemented via nightly compound loop.

Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>"

# 11. Push branch
echo "[compound] Pushing branch..."
git push -u origin "$BRANCH_NAME"

# 12. Create PR
echo "[compound] Creating pull request..."
PR_URL=$(gh pr create \
  --title "feat(agent): $TASK_DESC" \
  --body "## Summary
- Implemented task: $TASK_DESC
- From: \`agent/implementation_plan.md\` line $LINE_NUM

## Generated by
Nightly Compound Loop - $(date '+%Y-%m-%d %H:%M')

## Verification
- [ ] Typecheck passes
- [ ] Lint passes
- [ ] Manual review

---
Generated with Claude Code Compound Engineering" \
  --draft 2>&1) || {
  echo "[compound] Failed to create PR"
  "$SCRIPT_DIR/notify.sh" "Branch pushed but PR creation failed: $BRANCH_NAME" "Compound Warning"
  exit 1
}

echo "[compound] PR created: $PR_URL"

# 13. Return to main
git checkout main

# 14. Notify success
"$SCRIPT_DIR/notify.sh" "PR created: $TASK_DESC\n$PR_URL" "Compound Success"

echo "[compound] Complete!"
echo "PR: $PR_URL"
